name: 'Nightly Merge'

on:
  push:
    branches:
      - develop

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.2.0
      with:
        stable_branch: 'develop'
        development_branch: 'master'
        allow_ff: false
        user_email: icedmetal57@gmail.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
