name: 'Nightly Merge'

on:
  push:
    branches:
      - master

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
        run: git lfs checkout

    - name: Nightly Merge
      uses: ./.github/actions/merge-branches
      with:
        source_branch: 'master'
        target_branch: 'nightly'
        allow_ff: true
        allow_git_lfs: true
        push_token: 'Nightly_Merge'
      env:
        GITHUB_TOKEN: ${{ secrets.Nightly_Merge }}
        Nightly_Merge: ${{ secrets.Nightly_Merge }}