name: 'Nightly Merge'

on:
  push:
    branches:
      - master

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Nightly Merge
      uses: ./.github/actions/merge-branches
      with:
        source_branch: 'master'
        target_branch: 'develop'
        allow_ff: true
        push_token: 'NIGHTLY_MERGE'
      env:
        GITHUB_TOKEN: ${{ secrets.NIGHTLY_MERGE }}